!***********************************************************************
! This file is part of OpenMolcas.                                     *
!                                                                      *
! OpenMolcas is free software; you can redistribute it and/or modify   *
! it under the terms of the GNU Lesser General Public License, v. 2.1. *
! OpenMolcas is distributed in the hope that it will be useful, but it *
! is provided "as is" and without any express or implied warranties.   *
! For more details see the full text of the license in the file        *
! LICENSE or in <http://www.gnu.org/licenses/>.                        *
!                                                                      *
! Copyright (C) 2017, Quan Phung                                       *
!***********************************************************************
! Load text file 2RDM generated by DICE

subroutine dice_load2pdm( NAC, PT, CHEMROOT )

  IMPLICIT NONE
  INTEGER, INTENT(IN) :: NAC, CHEMROOT
  REAL*8, INTENT(OUT) :: PT( NAC, NAC, NAC, NAC )

  CHARACTER(LEN=30) :: file_2rdm

  INTEGER :: i, idx1, idx2, idx3, idx4, irdm, lu
  INTEGER :: nact
  character(len=10) :: rootindex

  PT = 0.0d0

  write(rootindex,"(I2)") chemroot-1
  file_2rdm="spatialRDM."//trim(adjustl(rootindex))//"."//trim(adjustl(rootindex))//".txt"
  file_2rdm=trim(adjustl(file_2rdm))

  call f_inquire(file_2rdm, irdm)
  if (.NOT. irdm) then
     write(6,'(1X,A15,I3,A16)') 'DICE> Root: ',CHEMROOT,' :: No 2RDM file'
     call abend()
  endif

  LU=40
  call molcas_open(LU,file_2rdm)

  read(LU,*) nact

  if (nact .NE. NAC) then
    write(6,*) 'DICE: DB> Wrong number of active orbitals'
    call abend()
  endif

  do i=1,nact**4
    read(LU,*) idx1, idx2, idx3, idx4, PT( idx1+1, idx3+1, idx4+1, idx2+1 )
  enddo

  close(LU)

end subroutine
