!***********************************************************************
! This file is part of OpenMolcas.                                     *
!                                                                      *
! OpenMolcas is free software; you can redistribute it and/or modify   *
! it under the terms of the GNU Lesser General Public License, v. 2.1. *
! OpenMolcas is distributed in the hope that it will be useful, but it *
! is provided "as is" and without any express or implied warranties.   *
! For more details see the full text of the license in the file        *
! LICENSE or in <http://www.gnu.org/licenses/>.                        *
!                                                                      *
! Copyright (C) 2018, Quan Phung                                       *
!***********************************************************************
! Load text file 3RDM generated by BLOCK

subroutine block_load3pdm_txt( NAC, PT, CHEMROOT, TRANS )

  IMPLICIT NONE
  INTEGER, INTENT(IN) :: NAC, CHEMROOT
  REAL*8, INTENT(OUT) :: PT( NAC, NAC, NAC, NAC, NAC, NAC )
  LOGICAL, INTENT(IN) :: TRANS
  REAL*8 :: PTtemp

  CHARACTER(LEN=50) :: file_3rdm

  INTEGER :: idx1, idx2, idx3, idx4, idx5, idx6, irdm, lu, ierr
  INTEGER :: nact
  character(len=10) :: rootindex

  call dcopy_(nac**6,0.0d0,0,PT,1)
!  PT = 0.0d0

  write(rootindex,"(I2)") chemroot-1
  if (trans) then
    file_3rdm="./node0/spatial_threepdm."//trim(adjustl(rootindex))//"."//trim(adjustl(rootindex))//".txt.trans"
  else
    file_3rdm="./node0/spatial_threepdm."//trim(adjustl(rootindex))//"."//trim(adjustl(rootindex))//".txt"
  endif
  file_3rdm=trim(adjustl(file_3rdm))

  call f_inquire(file_3rdm, irdm)
  if (.NOT. irdm) then
     write(6,'(1X,A15,I3,A16)') 'BLOCK> Root: ',CHEMROOT,' :: No 3RDM file'
     call abend()
  endif

  LU=40
  call molcas_open(LU,file_3rdm)

  read(LU,*) nact

! sort <i,j,k,l,m,n> (in row-major) to G(i,n,j,m,k,l) (in col-major)
! i.e. G(i,j,k,l,m,n) = <i,k,m,n,l,j>

  do
    read(LU,*,IOSTAT=ierr) idx1, idx2, idx3, idx4, idx5, idx6, PTtemp
    if (ierr == 0) then
      PT( idx1+1, idx6+1, idx2+1, idx5+1, idx3+1, idx4+1) = PTtemp
    else
      exit
    endif
  enddo

  close(LU)

end subroutine
